name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.0' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Get build cache
      uses: actions/cache@v2
      with:
        path: _build/test/
        key: build-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}

    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Run linter
      run: mix credo
    - name: Check formatting
      run: mix format --check-formatted
    - name: Test Coverage
      run: mix coveralls.json
    - uses: codecov/codecov-action@v2
      with:
        files: cover/excoveralls.json
        token: ${{ secrets.CODECOV_TOKEN }}
